In [17]:
###Code to get mode of a data
from collections import Counter
num_list=[1,1,1,1,2,2,2,3,3,5,8,9,7,7,6,5]
n=len(num_list)
data=Counter(num_list)
print(data)
get_data=dict(data)
print(get_data)
mode=[k for k,v in get_data.items() if v==max(list(get_data.values()))]
print(mode)

Counter({1: 4, 2: 3, 3: 2, 5: 2, 7: 2, 8: 1, 9: 1, 6: 1})
{1: 4, 2: 3, 3: 2, 5: 2, 8: 1, 9: 1, 7: 2, 6: 1}
[1]


In [42]:
import pandas as pd
url="https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
df=pd.read_csv(url)
print(df[1:8])


      Country  Region
0     Algeria  AFRICA
1      Angola  AFRICA
2       Benin  AFRICA
3    Botswana  AFRICA
4     Burkina  AFRICA
5     Burundi  AFRICA
6    Cameroon  AFRICA
7  Cape Verde  AFRICA


In [7]:
import numpy as np
matrix = np.random.randint(-1,1,size=(5,5))
print(matrix)


[[-1 -1  0  0 -1]
 [-1 -1 -1 -1  0]
 [-1  0  0  0 -1]
 [-1 -1  0  0 -1]
 [-1  0  0  0 -1]]


In [31]:
##############Create a 5X5 matrix with entries between -1 to 1 and multiply all negative numbers by -2 and all positive numbers by -1
import numpy as np
high = 1
low = -1
m,n = 5,5
mat = (high - low)*np.random.rand(m,n) + low
result = np.where(mat > 0, mat*-1, mat*-2)
print(result)


[[ 1.28125374  0.5646493   0.87241513 -0.64269341 -0.65223231]
 [-0.8878      0.76575238  1.43814615 -0.86494536 -0.3004241 ]
 [ 0.97632255  1.40199461  0.88184354 -0.5424124   0.87947513]
 [ 0.23226209  0.81243646  1.57137003  0.7022365  -0.94617003]
 [ 1.6674005   1.6738338   1.05378725  0.69163065 -0.99156806]]


In [ ]:
from scipy.stats import binom


In [4]:
############Create a function to get variance and std. deviation of data
import math
def variance(data, ddof=0):
    n = len(data)
    mean = sum(data) / n
    return sum((x - mean) ** 2 for x in data) / (n - ddof)
def stdev(data, ddof=0):
    return math.sqrt(variance(data, ddof))
###example
var=variance([4, 8, 6, 5, 3, 2, 8, 9, 2, 5], ddof=1)
sd=stdev([4, 8, 6, 5, 3, 2, 8, 9, 2, 5], ddof=1)
print(var, sd)

6.4 2.5298221281347035


In [13]:
#########Mean###################
def mean(data):
    return sum(data) / len(data)
#########Mode########################
def median(data):
    n = len(data)
    index = n // 2
    if n % 2:
        return sorted(data)[index]
    return sum(sorted(data)[index - 1:index + 1]) / 2
############std. deviation######################
import math
def variance(data, ddof=0):
    n = len(data)
    mean = sum(data) / n
    return sum((x - mean) ** 2 for x in data) / (n - ddof)
def stdev(data, ddof=0):
    return math.sqrt(variance(data, ddof))
##############Skewness##########################
def skew(data,ddof):
    return 3*(mean(data)-median(data))/stdev(data,ddof)
####Example#################3
data=[4, 8, 6, 5, 3, 2, 8, 9, 2, 5]
ddof=1
print(skew(data,ddof))

0.23717082451262866


In [27]:
##########Doing paired sample T-test for the following data
Before_Course=[44,40,61,52,32,44,70,41,67,72,53,72]
After_Course=[53,38,69,57,46,39,73,48,73,74,60,78]
###Converting the list to csv.................
import pandas as pd
Before_Course=pd.DataFrame(Before_Course) 
Before_Course.to_csv('Before.csv') 
After_Course=pd.DataFrame(After_Course) 
After_Course.to_csv('After.csv') 
##exporting csv to pandas datafram
Before=pd.read_csv("Before.csv")
After=pd.read_csv("After.csv")
Before=Before.iloc[:, 1]
After=After.iloc[:, 1]
import scipy.stats as stats
stats.ttest_rel(Before, After)


########Result Conclusion###################
#Since this p-value is less than our significance level α = 0.05, we reject the null hypothesis.


0     44
1     40
2     61
3     52
4     32
5     44
6     70
7     41
8     67
9     72
10    53
11    72
Name: 0, dtype: int64


Ttest_relResult(statistic=-3.445359719553577, pvalue=0.005472667818346521)